### ISSUE TITLE
Trivial - fix typo

### ISSUE THREAD

**Issue by jcopson** [sergiomarotco/Network-segmentation-cheat-sheet#11]
Fix typo of "sanbox" under "advantages" section of Level 3 segmentation.

**Comment by sergiomarotco** [comment]
Thanks comrade!

**Comment by sergiomarotco** [comment]
https://github.com/sergiomarotco/Network-segmentation-cheat-sheet/commit/9fefb7e52cf24aaaecedc0d982a0536f5579728c
