### ISSUE TITLE
SOAR/SIRP

### ISSUE THREAD

**Issue by cyb3rxp** [sergiomarotco/Network-segmentation-cheat-sheet#23]
Hi,
thanks for the drawings.
FYI, IRP DB and SOAR DB do point to the same thing, since SOAR encompasses SIRP, as per the Gartner's definition of SOAR: https://github.com/cyb3rxp/awesome-soc#what-is-soar
HTH.
Regards,

**Comment by sergiomarotco** [comment]
Hi, good, i fix later.
